Continent.create!([
  {name: "Africa"},
  {name: "Antarctica"},
  {name: "Asia"},
  {name: "Europe"},
  {name: "North America"},
  {name: "Oceania"},
  {name: "South America"}
])
Country.create!([
  {code: "AD", name: "Andorra", native: "Andorra", phone: "376", capital: "Andorra la Vella", currency: "EUR", continent_id: 4},
  {code: "AE", name: "United Arab Emirates", native: "دولة الإمارات العربية المتحدة", phone: "971", capital: "Abu Dhabi", currency: "AED", continent_id: 3},
  {code: "AF", name: "Afghanistan", native: "افغانستان", phone: "93", capital: "Kabul", currency: "AFN", continent_id: 3},
  {code: "AG", name: "Antigua and Barbuda", native: "Antigua and Barbuda", phone: "1268", capital: "Saint John's", currency: "XCD", continent_id: 5},
  {code: "AI", name: "Anguilla", native: "Anguilla", phone: "1264", capital: "The Valley", currency: "XCD", continent_id: 5},
  {code: "AL", name: "Albania", native: "Shqipëria", phone: "355", capital: "Tirana", currency: "ALL", continent_id: 4},
  {code: "AM", name: "Armenia", native: "Հայաստան", phone: "374", capital: "Yerevan", currency: "AMD", continent_id: 3},
  {code: "AO", name: "Angola", native: "Angola", phone: "244", capital: "Luanda", currency: "AOA", continent_id: 1},
  {code: "AQ", name: "Antarctica", native: "Antarctica", phone: "672", capital: "", currency: "", continent_id: 2},
  {code: "AR", name: "Argentina", native: "Argentina", phone: "54", capital: "Buenos Aires", currency: "ARS", continent_id: 7},
  {code: "AS", name: "American Samoa", native: "American Samoa", phone: "1684", capital: "Pago Pago", currency: "USD", continent_id: 6},
  {code: "AT", name: "Austria", native: "Österreich", phone: "43", capital: "Vienna", currency: "EUR", continent_id: 4},
  {code: "AU", name: "Australia", native: "Australia", phone: "61", capital: "Canberra", currency: "AUD", continent_id: 6},
  {code: "AW", name: "Aruba", native: "Aruba", phone: "297", capital: "Oranjestad", currency: "AWG", continent_id: 5},
  {code: "AX", name: "Åland", native: "Åland", phone: "358", capital: "Mariehamn", currency: "EUR", continent_id: 4},
  {code: "AZ", name: "Azerbaijan", native: "Azərbaycan", phone: "994", capital: "Baku", currency: "AZN", continent_id: 3},
  {code: "BA", name: "Bosnia and Herzegovina", native: "Bosna i Hercegovina", phone: "387", capital: "Sarajevo", currency: "BAM", continent_id: 4},
  {code: "BB", name: "Barbados", native: "Barbados", phone: "1246", capital: "Bridgetown", currency: "BBD", continent_id: 5},
  {code: "BD", name: "Bangladesh", native: "Bangladesh", phone: "880", capital: "Dhaka", currency: "BDT", continent_id: 3},
  {code: "BE", name: "Belgium", native: "België", phone: "32", capital: "Brussels", currency: "EUR", continent_id: 4},
  {code: "BF", name: "Burkina Faso", native: "Burkina Faso", phone: "226", capital: "Ouagadougou", currency: "XOF", continent_id: 1},
  {code: "BG", name: "Bulgaria", native: "България", phone: "359", capital: "Sofia", currency: "BGN", continent_id: 4},
  {code: "BH", name: "Bahrain", native: "‏البحرين", phone: "973", capital: "Manama", currency: "BHD", continent_id: 3},
  {code: "BI", name: "Burundi", native: "Burundi", phone: "257", capital: "Bujumbura", currency: "BIF", continent_id: 1},
  {code: "BJ", name: "Benin", native: "Bénin", phone: "229", capital: "Porto-Novo", currency: "XOF", continent_id: 1},
  {code: "BL", name: "Saint Barthélemy", native: "Saint-Barthélemy", phone: "590", capital: "Gustavia", currency: "EUR", continent_id: 5},
  {code: "BM", name: "Bermuda", native: "Bermuda", phone: "1441", capital: "Hamilton", currency: "BMD", continent_id: 5},
  {code: "BN", name: "Brunei", native: "Negara Brunei Darussalam", phone: "673", capital: "Bandar Seri Begawan", currency: "BND", continent_id: 3},
  {code: "BO", name: "Bolivia", native: "Bolivia", phone: "591", capital: "Sucre", currency: "BOB,BOV", continent_id: 7},
  {code: "BQ", name: "Bonaire", native: "Bonaire", phone: "5997", capital: "Kralendijk", currency: "USD", continent_id: 5},
  {code: "BR", name: "Brazil", native: "Brasil", phone: "55", capital: "Brasília", currency: "BRL", continent_id: 7},
  {code: "BS", name: "Bahamas", native: "Bahamas", phone: "1242", capital: "Nassau", currency: "BSD", continent_id: 5},
  {code: "BT", name: "Bhutan", native: "ʼbrug-yul", phone: "975", capital: "Thimphu", currency: "BTN,INR", continent_id: 3},
  {code: "BV", name: "Bouvet Island", native: "Bouvetøya", phone: "47", capital: "", currency: "NOK", continent_id: 2},
  {code: "BW", name: "Botswana", native: "Botswana", phone: "267", capital: "Gaborone", currency: "BWP", continent_id: 1},
  {code: "BY", name: "Belarus", native: "Белару́сь", phone: "375", capital: "Minsk", currency: "BYR", continent_id: 4},
  {code: "BZ", name: "Belize", native: "Belize", phone: "501", capital: "Belmopan", currency: "BZD", continent_id: 5},
  {code: "CA", name: "Canada", native: "Canada", phone: "1", capital: "Ottawa", currency: "CAD", continent_id: 5},
  {code: "CC", name: "Cocos [Keeling] Islands", native: "Cocos (Keeling) Islands", phone: "61", capital: "West Island", currency: "AUD", continent_id: 3},
  {code: "CD", name: "Democratic Republic of the Congo", native: "République démocratique du Congo", phone: "243", capital: "Kinshasa", currency: "CDF", continent_id: 1},
  {code: "CF", name: "Central African Republic", native: "Ködörösêse tî Bêafrîka", phone: "236", capital: "Bangui", currency: "XAF", continent_id: 1},
  {code: "CG", name: "Republic of the Congo", native: "République du Congo", phone: "242", capital: "Brazzaville", currency: "XAF", continent_id: 1},
  {code: "CH", name: "Switzerland", native: "Schweiz", phone: "41", capital: "Bern", currency: "CHE,CHF,CHW", continent_id: 4},
  {code: "CI", name: "Ivory Coast", native: "Côte d'Ivoire", phone: "225", capital: "Yamoussoukro", currency: "XOF", continent_id: 1},
  {code: "CK", name: "Cook Islands", native: "Cook Islands", phone: "682", capital: "Avarua", currency: "NZD", continent_id: 6},
  {code: "CL", name: "Chile", native: "Chile", phone: "56", capital: "Santiago", currency: "CLF,CLP", continent_id: 7},
  {code: "CM", name: "Cameroon", native: "Cameroon", phone: "237", capital: "Yaoundé", currency: "XAF", continent_id: 1},
  {code: "CN", name: "China", native: "中国", phone: "86", capital: "Beijing", currency: "CNY", continent_id: 3},
  {code: "CO", name: "Colombia", native: "Colombia", phone: "57", capital: "Bogotá", currency: "COP", continent_id: 7},
  {code: "CR", name: "Costa Rica", native: "Costa Rica", phone: "506", capital: "San José", currency: "CRC", continent_id: 5},
  {code: "CU", name: "Cuba", native: "Cuba", phone: "53", capital: "Havana", currency: "CUC,CUP", continent_id: 5},
  {code: "CV", name: "Cape Verde", native: "Cabo Verde", phone: "238", capital: "Praia", currency: "CVE", continent_id: 1},
  {code: "CW", name: "Curacao", native: "Curaçao", phone: "5999", capital: "Willemstad", currency: "ANG", continent_id: 5},
  {code: "CX", name: "Christmas Island", native: "Christmas Island", phone: "61", capital: "Flying Fish Cove", currency: "AUD", continent_id: 3},
  {code: "CY", name: "Cyprus", native: "Κύπρος", phone: "357", capital: "Nicosia", currency: "EUR", continent_id: 4},
  {code: "CZ", name: "Czech Republic", native: "Česká republika", phone: "420", capital: "Prague", currency: "CZK", continent_id: 4},
  {code: "DE", name: "Germany", native: "Deutschland", phone: "49", capital: "Berlin", currency: "EUR", continent_id: 4},
  {code: "DJ", name: "Djibouti", native: "Djibouti", phone: "253", capital: "Djibouti", currency: "DJF", continent_id: 1},
  {code: "DK", name: "Denmark", native: "Danmark", phone: "45", capital: "Copenhagen", currency: "DKK", continent_id: 4},
  {code: "DM", name: "Dominica", native: "Dominica", phone: "1767", capital: "Roseau", currency: "XCD", continent_id: 5},
  {code: "DO", name: "Dominican Republic", native: "República Dominicana", phone: "1809,1829,1849", capital: "Santo Domingo", currency: "DOP", continent_id: 5},
  {code: "DZ", name: "Algeria", native: "الجزائر", phone: "213", capital: "Algiers", currency: "DZD", continent_id: 1},
  {code: "EC", name: "Ecuador", native: "Ecuador", phone: "593", capital: "Quito", currency: "USD", continent_id: 7},
  {code: "EE", name: "Estonia", native: "Eesti", phone: "372", capital: "Tallinn", currency: "EUR", continent_id: 4},
  {code: "EG", name: "Egypt", native: "مصر‎", phone: "20", capital: "Cairo", currency: "EGP", continent_id: 1},
  {code: "EH", name: "Western Sahara", native: "الصحراء الغربية", phone: "212", capital: "El Aaiún", currency: "MAD,DZD,MRO", continent_id: 1},
  {code: "ER", name: "Eritrea", native: "ኤርትራ", phone: "291", capital: "Asmara", currency: "ERN", continent_id: 1},
  {code: "ES", name: "Spain", native: "España", phone: "34", capital: "Madrid", currency: "EUR", continent_id: 4},
  {code: "ET", name: "Ethiopia", native: "ኢትዮጵያ", phone: "251", capital: "Addis Ababa", currency: "ETB", continent_id: 1},
  {code: "FI", name: "Finland", native: "Suomi", phone: "358", capital: "Helsinki", currency: "EUR", continent_id: 4},
  {code: "FJ", name: "Fiji", native: "Fiji", phone: "679", capital: "Suva", currency: "FJD", continent_id: 6},
  {code: "FK", name: "Falkland Islands", native: "Falkland Islands", phone: "500", capital: "Stanley", currency: "FKP", continent_id: 7},
  {code: "FM", name: "Micronesia", native: "Micronesia", phone: "691", capital: "Palikir", currency: "USD", continent_id: 6},
  {code: "FO", name: "Faroe Islands", native: "Føroyar", phone: "298", capital: "Tórshavn", currency: "DKK", continent_id: 4},
  {code: "FR", name: "France", native: "France", phone: "33", capital: "Paris", currency: "EUR", continent_id: 4},
  {code: "GA", name: "Gabon", native: "Gabon", phone: "241", capital: "Libreville", currency: "XAF", continent_id: 1},
  {code: "GB", name: "United Kingdom", native: "United Kingdom", phone: "44", capital: "London", currency: "GBP", continent_id: 4},
  {code: "GD", name: "Grenada", native: "Grenada", phone: "1473", capital: "St. George's", currency: "XCD", continent_id: 5},
  {code: "GE", name: "Georgia", native: "საქართველო", phone: "995", capital: "Tbilisi", currency: "GEL", continent_id: 3},
  {code: "GF", name: "French Guiana", native: "Guyane française", phone: "594", capital: "Cayenne", currency: "EUR", continent_id: 7},
  {code: "GG", name: "Guernsey", native: "Guernsey", phone: "44", capital: "St. Peter Port", currency: "GBP", continent_id: 4},
  {code: "GH", name: "Ghana", native: "Ghana", phone: "233", capital: "Accra", currency: "GHS", continent_id: 1},
  {code: "GI", name: "Gibraltar", native: "Gibraltar", phone: "350", capital: "Gibraltar", currency: "GIP", continent_id: 4},
  {code: "GL", name: "Greenland", native: "Kalaallit Nunaat", phone: "299", capital: "Nuuk", currency: "DKK", continent_id: 5},
  {code: "GM", name: "Gambia", native: "Gambia", phone: "220", capital: "Banjul", currency: "GMD", continent_id: 1},
  {code: "GN", name: "Guinea", native: "Guinée", phone: "224", capital: "Conakry", currency: "GNF", continent_id: 1},
  {code: "GP", name: "Guadeloupe", native: "Guadeloupe", phone: "590", capital: "Basse-Terre", currency: "EUR", continent_id: 5},
  {code: "GQ", name: "Equatorial Guinea", native: "Guinea Ecuatorial", phone: "240", capital: "Malabo", currency: "XAF", continent_id: 1},
  {code: "GR", name: "Greece", native: "Ελλάδα", phone: "30", capital: "Athens", currency: "EUR", continent_id: 4},
  {code: "GS", name: "South Georgia and the South Sandwich Islands", native: "South Georgia", phone: "500", capital: "King Edward Point", currency: "GBP", continent_id: 2},
  {code: "GT", name: "Guatemala", native: "Guatemala", phone: "502", capital: "Guatemala City", currency: "GTQ", continent_id: 5},
  {code: "GU", name: "Guam", native: "Guam", phone: "1671", capital: "Hagåtña", currency: "USD", continent_id: 6},
  {code: "GW", name: "Guinea-Bissau", native: "Guiné-Bissau", phone: "245", capital: "Bissau", currency: "XOF", continent_id: 1},
  {code: "GY", name: "Guyana", native: "Guyana", phone: "592", capital: "Georgetown", currency: "GYD", continent_id: 7},
  {code: "HK", name: "Hong Kong", native: "香港", phone: "852", capital: "City of Victoria", currency: "HKD", continent_id: 3},
  {code: "HM", name: "Heard Island and McDonald Islands", native: "Heard Island and McDonald Islands", phone: "61", capital: "", currency: "AUD", continent_id: 2},
  {code: "HN", name: "Honduras", native: "Honduras", phone: "504", capital: "Tegucigalpa", currency: "HNL", continent_id: 5},
  {code: "HR", name: "Croatia", native: "Hrvatska", phone: "385", capital: "Zagreb", currency: "HRK", continent_id: 4},
  {code: "HT", name: "Haiti", native: "Haïti", phone: "509", capital: "Port-au-Prince", currency: "HTG,USD", continent_id: 5},
  {code: "HU", name: "Hungary", native: "Magyarország", phone: "36", capital: "Budapest", currency: "HUF", continent_id: 4},
  {code: "ID", name: "Indonesia", native: "Indonesia", phone: "62", capital: "Jakarta", currency: "IDR", continent_id: 3},
  {code: "IE", name: "Ireland", native: "Éire", phone: "353", capital: "Dublin", currency: "EUR", continent_id: 4},
  {code: "IL", name: "Israel", native: "יִשְׂרָאֵל", phone: "972", capital: "Jerusalem", currency: "ILS", continent_id: 3},
  {code: "IM", name: "Isle of Man", native: "Isle of Man", phone: "44", capital: "Douglas", currency: "GBP", continent_id: 4},
  {code: "IN", name: "India", native: "भारत", phone: "91", capital: "New Delhi", currency: "INR", continent_id: 3},
  {code: "IO", name: "British Indian Ocean Territory", native: "British Indian Ocean Territory", phone: "246", capital: "Diego Garcia", currency: "USD", continent_id: 3},
  {code: "IQ", name: "Iraq", native: "العراق", phone: "964", capital: "Baghdad", currency: "IQD", continent_id: 3},
  {code: "IR", name: "Iran", native: "ایران", phone: "98", capital: "Tehran", currency: "IRR", continent_id: 3},
  {code: "IS", name: "Iceland", native: "Ísland", phone: "354", capital: "Reykjavik", currency: "ISK", continent_id: 4},
  {code: "IT", name: "Italy", native: "Italia", phone: "39", capital: "Rome", currency: "EUR", continent_id: 4},
  {code: "JE", name: "Jersey", native: "Jersey", phone: "44", capital: "Saint Helier", currency: "GBP", continent_id: 4},
  {code: "JM", name: "Jamaica", native: "Jamaica", phone: "1876", capital: "Kingston", currency: "JMD", continent_id: 5},
  {code: "JO", name: "Jordan", native: "الأردن", phone: "962", capital: "Amman", currency: "JOD", continent_id: 3},
  {code: "JP", name: "Japan", native: "日本", phone: "81", capital: "Tokyo", currency: "JPY", continent_id: 3},
  {code: "KE", name: "Kenya", native: "Kenya", phone: "254", capital: "Nairobi", currency: "KES", continent_id: 1},
  {code: "KG", name: "Kyrgyzstan", native: "Кыргызстан", phone: "996", capital: "Bishkek", currency: "KGS", continent_id: 3},
  {code: "KH", name: "Cambodia", native: "Kâmpŭchéa", phone: "855", capital: "Phnom Penh", currency: "KHR", continent_id: 3},
  {code: "KI", name: "Kiribati", native: "Kiribati", phone: "686", capital: "South Tarawa", currency: "AUD", continent_id: 6},
  {code: "KM", name: "Comoros", native: "Komori", phone: "269", capital: "Moroni", currency: "KMF", continent_id: 1},
  {code: "KN", name: "Saint Kitts and Nevis", native: "Saint Kitts and Nevis", phone: "1869", capital: "Basseterre", currency: "XCD", continent_id: 5},
  {code: "KP", name: "North Korea", native: "북한", phone: "850", capital: "Pyongyang", currency: "KPW", continent_id: 3},
  {code: "KR", name: "South Korea", native: "대한민국", phone: "82", capital: "Seoul", currency: "KRW", continent_id: 3},
  {code: "KW", name: "Kuwait", native: "الكويت", phone: "965", capital: "Kuwait City", currency: "KWD", continent_id: 3},
  {code: "KY", name: "Cayman Islands", native: "Cayman Islands", phone: "1345", capital: "George Town", currency: "KYD", continent_id: 5},
  {code: "KZ", name: "Kazakhstan", native: "Қазақстан", phone: "76,77", capital: "Astana", currency: "KZT", continent_id: 3},
  {code: "LA", name: "Laos", native: "ສປປລາວ", phone: "856", capital: "Vientiane", currency: "LAK", continent_id: 3},
  {code: "LB", name: "Lebanon", native: "لبنان", phone: "961", capital: "Beirut", currency: "LBP", continent_id: 3},
  {code: "LC", name: "Saint Lucia", native: "Saint Lucia", phone: "1758", capital: "Castries", currency: "XCD", continent_id: 5},
  {code: "LI", name: "Liechtenstein", native: "Liechtenstein", phone: "423", capital: "Vaduz", currency: "CHF", continent_id: 4},
  {code: "LK", name: "Sri Lanka", native: "śrī laṃkāva", phone: "94", capital: "Colombo", currency: "LKR", continent_id: 3},
  {code: "LR", name: "Liberia", native: "Liberia", phone: "231", capital: "Monrovia", currency: "LRD", continent_id: 1},
  {code: "LS", name: "Lesotho", native: "Lesotho", phone: "266", capital: "Maseru", currency: "LSL,ZAR", continent_id: 1},
  {code: "LT", name: "Lithuania", native: "Lietuva", phone: "370", capital: "Vilnius", currency: "LTL", continent_id: 4},
  {code: "LU", name: "Luxembourg", native: "Luxembourg", phone: "352", capital: "Luxembourg", currency: "EUR", continent_id: 4},
  {code: "LV", name: "Latvia", native: "Latvija", phone: "371", capital: "Riga", currency: "EUR", continent_id: 4},
  {code: "LY", name: "Libya", native: "‏ليبيا", phone: "218", capital: "Tripoli", currency: "LYD", continent_id: 1},
  {code: "MA", name: "Morocco", native: "المغرب", phone: "212", capital: "Rabat", currency: "MAD", continent_id: 1},
  {code: "MC", name: "Monaco", native: "Monaco", phone: "377", capital: "Monaco", currency: "EUR", continent_id: 4},
  {code: "MD", name: "Moldova", native: "Moldova", phone: "373", capital: "Chișinău", currency: "MDL", continent_id: 4},
  {code: "ME", name: "Montenegro", native: "Црна Гора", phone: "382", capital: "Podgorica", currency: "EUR", continent_id: 4},
  {code: "MF", name: "Saint Martin", native: "Saint-Martin", phone: "590", capital: "Marigot", currency: "EUR", continent_id: 5},
  {code: "MG", name: "Madagascar", native: "Madagasikara", phone: "261", capital: "Antananarivo", currency: "MGA", continent_id: 1},
  {code: "MH", name: "Marshall Islands", native: "M̧ajeļ", phone: "692", capital: "Majuro", currency: "USD", continent_id: 6},
  {code: "MK", name: "Macedonia", native: "Македонија", phone: "389", capital: "Skopje", currency: "MKD", continent_id: 4},
  {code: "ML", name: "Mali", native: "Mali", phone: "223", capital: "Bamako", currency: "XOF", continent_id: 1},
  {code: "MM", name: "Myanmar [Burma]", native: "Myanma", phone: "95", capital: "Naypyidaw", currency: "MMK", continent_id: 3},
  {code: "MN", name: "Mongolia", native: "Монгол улс", phone: "976", capital: "Ulan Bator", currency: "MNT", continent_id: 3},
  {code: "MO", name: "Macao", native: "澳門", phone: "853", capital: "", currency: "MOP", continent_id: 3},
  {code: "MP", name: "Northern Mariana Islands", native: "Northern Mariana Islands", phone: "1670", capital: "Saipan", currency: "USD", continent_id: 6},
  {code: "MQ", name: "Martinique", native: "Martinique", phone: "596", capital: "Fort-de-France", currency: "EUR", continent_id: 5},
  {code: "MR", name: "Mauritania", native: "موريتانيا", phone: "222", capital: "Nouakchott", currency: "MRO", continent_id: 1},
  {code: "MS", name: "Montserrat", native: "Montserrat", phone: "1664", capital: "Plymouth", currency: "XCD", continent_id: 5},
  {code: "MT", name: "Malta", native: "Malta", phone: "356", capital: "Valletta", currency: "EUR", continent_id: 4},
  {code: "MU", name: "Mauritius", native: "Maurice", phone: "230", capital: "Port Louis", currency: "MUR", continent_id: 1},
  {code: "MV", name: "Maldives", native: "Maldives", phone: "960", capital: "Malé", currency: "MVR", continent_id: 3},
  {code: "MW", name: "Malawi", native: "Malawi", phone: "265", capital: "Lilongwe", currency: "MWK", continent_id: 1},
  {code: "MX", name: "Mexico", native: "México", phone: "52", capital: "Mexico City", currency: "MXN", continent_id: 5},
  {code: "MY", name: "Malaysia", native: "Malaysia", phone: "60", capital: "Kuala Lumpur", currency: "MYR", continent_id: 3},
  {code: "MZ", name: "Mozambique", native: "Moçambique", phone: "258", capital: "Maputo", currency: "MZN", continent_id: 1},
  {code: "NA", name: "Namibia", native: "Namibia", phone: "264", capital: "Windhoek", currency: "NAD,ZAR", continent_id: 1},
  {code: "NC", name: "New Caledonia", native: "Nouvelle-Calédonie", phone: "687", capital: "Nouméa", currency: "XPF", continent_id: 6},
  {code: "NE", name: "Niger", native: "Niger", phone: "227", capital: "Niamey", currency: "XOF", continent_id: 1},
  {code: "NF", name: "Norfolk Island", native: "Norfolk Island", phone: "672", capital: "Kingston", currency: "AUD", continent_id: 6},
  {code: "NG", name: "Nigeria", native: "Nigeria", phone: "234", capital: "Abuja", currency: "NGN", continent_id: 1},
  {code: "NI", name: "Nicaragua", native: "Nicaragua", phone: "505", capital: "Managua", currency: "NIO", continent_id: 5},
  {code: "NL", name: "Netherlands", native: "Nederland", phone: "31", capital: "Amsterdam", currency: "EUR", continent_id: 4},
  {code: "NO", name: "Norway", native: "Norge", phone: "47", capital: "Oslo", currency: "NOK", continent_id: 4},
  {code: "NP", name: "Nepal", native: "नपल", phone: "977", capital: "Kathmandu", currency: "NPR", continent_id: 3},
  {code: "NR", name: "Nauru", native: "Nauru", phone: "674", capital: "Yaren", currency: "AUD", continent_id: 6},
  {code: "NU", name: "Niue", native: "Niuē", phone: "683", capital: "Alofi", currency: "NZD", continent_id: 6},
  {code: "NZ", name: "New Zealand", native: "New Zealand", phone: "64", capital: "Wellington", currency: "NZD", continent_id: 6},
  {code: "OM", name: "Oman", native: "عمان", phone: "968", capital: "Muscat", currency: "OMR", continent_id: 3},
  {code: "PA", name: "Panama", native: "Panamá", phone: "507", capital: "Panama City", currency: "PAB,USD", continent_id: 5},
  {code: "PE", name: "Peru", native: "Perú", phone: "51", capital: "Lima", currency: "PEN", continent_id: 7},
  {code: "PF", name: "French Polynesia", native: "Polynésie française", phone: "689", capital: "Papeetē", currency: "XPF", continent_id: 6},
  {code: "PG", name: "Papua New Guinea", native: "Papua Niugini", phone: "675", capital: "Port Moresby", currency: "PGK", continent_id: 6},
  {code: "PH", name: "Philippines", native: "Pilipinas", phone: "63", capital: "Manila", currency: "PHP", continent_id: 3},
  {code: "PK", name: "Pakistan", native: "Pakistan", phone: "92", capital: "Islamabad", currency: "PKR", continent_id: 3},
  {code: "PL", name: "Poland", native: "Polska", phone: "48", capital: "Warsaw", currency: "PLN", continent_id: 4},
  {code: "PM", name: "Saint Pierre and Miquelon", native: "Saint-Pierre-et-Miquelon", phone: "508", capital: "Saint-Pierre", currency: "EUR", continent_id: 5},
  {code: "PN", name: "Pitcairn Islands", native: "Pitcairn Islands", phone: "64", capital: "Adamstown", currency: "NZD", continent_id: 6},
  {code: "PR", name: "Puerto Rico", native: "Puerto Rico", phone: "1787,1939", capital: "San Juan", currency: "USD", continent_id: 5},
  {code: "PS", name: "Palestine", native: "فلسطين", phone: "970", capital: "Ramallah", currency: "ILS", continent_id: 3},
  {code: "PT", name: "Portugal", native: "Portugal", phone: "351", capital: "Lisbon", currency: "EUR", continent_id: 4},
  {code: "PW", name: "Palau", native: "Palau", phone: "680", capital: "Ngerulmud", currency: "USD", continent_id: 6},
  {code: "PY", name: "Paraguay", native: "Paraguay", phone: "595", capital: "Asunción", currency: "PYG", continent_id: 7},
  {code: "QA", name: "Qatar", native: "قطر", phone: "974", capital: "Doha", currency: "QAR", continent_id: 3},
  {code: "RE", name: "Réunion", native: "La Réunion", phone: "262", capital: "Saint-Denis", currency: "EUR", continent_id: 1},
  {code: "RO", name: "Romania", native: "România", phone: "40", capital: "Bucharest", currency: "RON", continent_id: 4},
  {code: "RS", name: "Serbia", native: "Србија", phone: "381", capital: "Belgrade", currency: "RSD", continent_id: 4},
  {code: "RU", name: "Russia", native: "Россия", phone: "7", capital: "Moscow", currency: "RUB", continent_id: 4},
  {code: "RW", name: "Rwanda", native: "Rwanda", phone: "250", capital: "Kigali", currency: "RWF", continent_id: 1},
  {code: "SA", name: "Saudi Arabia", native: "العربية السعودية", phone: "966", capital: "Riyadh", currency: "SAR", continent_id: 3},
  {code: "SB", name: "Solomon Islands", native: "Solomon Islands", phone: "677", capital: "Honiara", currency: "SBD", continent_id: 6},
  {code: "SC", name: "Seychelles", native: "Seychelles", phone: "248", capital: "Victoria", currency: "SCR", continent_id: 1},
  {code: "SD", name: "Sudan", native: "السودان", phone: "249", capital: "Khartoum", currency: "SDG", continent_id: 1},
  {code: "SE", name: "Sweden", native: "Sverige", phone: "46", capital: "Stockholm", currency: "SEK", continent_id: 4},
  {code: "SG", name: "Singapore", native: "Singapore", phone: "65", capital: "Singapore", currency: "SGD", continent_id: 3},
  {code: "SH", name: "Saint Helena", native: "Saint Helena", phone: "290", capital: "Jamestown", currency: "SHP", continent_id: 1},
  {code: "SI", name: "Slovenia", native: "Slovenija", phone: "386", capital: "Ljubljana", currency: "EUR", continent_id: 4},
  {code: "SJ", name: "Svalbard and Jan Mayen", native: "Svalbard og Jan Mayen", phone: "4779", capital: "Longyearbyen", currency: "NOK", continent_id: 4},
  {code: "SK", name: "Slovakia", native: "Slovensko", phone: "421", capital: "Bratislava", currency: "EUR", continent_id: 4},
  {code: "SL", name: "Sierra Leone", native: "Sierra Leone", phone: "232", capital: "Freetown", currency: "SLL", continent_id: 1},
  {code: "SM", name: "San Marino", native: "San Marino", phone: "378", capital: "City of San Marino", currency: "EUR", continent_id: 4},
  {code: "SN", name: "Senegal", native: "Sénégal", phone: "221", capital: "Dakar", currency: "XOF", continent_id: 1},
  {code: "SO", name: "Somalia", native: "Soomaaliya", phone: "252", capital: "Mogadishu", currency: "SOS", continent_id: 1},
  {code: "SR", name: "Suriname", native: "Suriname", phone: "597", capital: "Paramaribo", currency: "SRD", continent_id: 7},
  {code: "SS", name: "South Sudan", native: "South Sudan", phone: "211", capital: "Juba", currency: "SSP", continent_id: 1},
  {code: "ST", name: "São Tomé and Príncipe", native: "São Tomé e Príncipe", phone: "239", capital: "São Tomé", currency: "STD", continent_id: 1},
  {code: "SV", name: "El Salvador", native: "El Salvador", phone: "503", capital: "San Salvador", currency: "SVC,USD", continent_id: 5},
  {code: "SX", name: "Sint Maarten", native: "Sint Maarten", phone: "1721", capital: "Philipsburg", currency: "ANG", continent_id: 5},
  {code: "SY", name: "Syria", native: "سوريا", phone: "963", capital: "Damascus", currency: "SYP", continent_id: 3},
  {code: "SZ", name: "Swaziland", native: "Swaziland", phone: "268", capital: "Lobamba", currency: "SZL", continent_id: 1},
  {code: "TC", name: "Turks and Caicos Islands", native: "Turks and Caicos Islands", phone: "1649", capital: "Cockburn Town", currency: "USD", continent_id: 5},
  {code: "TD", name: "Chad", native: "Tchad", phone: "235", capital: "N'Djamena", currency: "XAF", continent_id: 1},
  {code: "TF", name: "French Southern Territories", native: "Territoire des Terres australes et antarctiques fr", phone: "262", capital: "Port-aux-Français", currency: "EUR", continent_id: 2},
  {code: "TG", name: "Togo", native: "Togo", phone: "228", capital: "Lomé", currency: "XOF", continent_id: 1},
  {code: "TH", name: "Thailand", native: "ประเทศไทย", phone: "66", capital: "Bangkok", currency: "THB", continent_id: 3},
  {code: "TJ", name: "Tajikistan", native: "Тоҷикистон", phone: "992", capital: "Dushanbe", currency: "TJS", continent_id: 3},
  {code: "TK", name: "Tokelau", native: "Tokelau", phone: "690", capital: "Fakaofo", currency: "NZD", continent_id: 6},
  {code: "TL", name: "East Timor", native: "Timor-Leste", phone: "670", capital: "Dili", currency: "USD", continent_id: 6},
  {code: "TM", name: "Turkmenistan", native: "Türkmenistan", phone: "993", capital: "Ashgabat", currency: "TMT", continent_id: 3},
  {code: "TN", name: "Tunisia", native: "تونس", phone: "216", capital: "Tunis", currency: "TND", continent_id: 1},
  {code: "TO", name: "Tonga", native: "Tonga", phone: "676", capital: "Nuku'alofa", currency: "TOP", continent_id: 6},
  {code: "TR", name: "Turkey", native: "Türkiye", phone: "90", capital: "Ankara", currency: "TRY", continent_id: 3},
  {code: "TT", name: "Trinidad and Tobago", native: "Trinidad and Tobago", phone: "1868", capital: "Port of Spain", currency: "TTD", continent_id: 5},
  {code: "TV", name: "Tuvalu", native: "Tuvalu", phone: "688", capital: "Funafuti", currency: "AUD", continent_id: 6},
  {code: "TW", name: "Taiwan", native: "臺灣", phone: "886", capital: "Taipei", currency: "TWD", continent_id: 3},
  {code: "TZ", name: "Tanzania", native: "Tanzania", phone: "255", capital: "Dodoma", currency: "TZS", continent_id: 1},
  {code: "UA", name: "Ukraine", native: "Україна", phone: "380", capital: "Kyiv", currency: "UAH", continent_id: 4},
  {code: "UG", name: "Uganda", native: "Uganda", phone: "256", capital: "Kampala", currency: "UGX", continent_id: 1},
  {code: "UM", name: "U.S. Minor Outlying Islands", native: "United States Minor Outlying Islands", phone: "1", capital: "", currency: "USD", continent_id: 6},
  {code: "US", name: "United States", native: "United States", phone: "1", capital: "Washington D.C.", currency: "USD,USN,USS", continent_id: 5},
  {code: "UY", name: "Uruguay", native: "Uruguay", phone: "598", capital: "Montevideo", currency: "UYI,UYU", continent_id: 7},
  {code: "UZ", name: "Uzbekistan", native: "O‘zbekiston", phone: "998", capital: "Tashkent", currency: "UZS", continent_id: 3},
  {code: "VA", name: "Vatican City", native: "Vaticano", phone: "39066,379", capital: "Vatican City", currency: "EUR", continent_id: 4},
  {code: "VC", name: "Saint Vincent and the Grenadines", native: "Saint Vincent and the Grenadines", phone: "1784", capital: "Kingstown", currency: "XCD", continent_id: 5},
  {code: "VE", name: "Venezuela", native: "Venezuela", phone: "58", capital: "Caracas", currency: "VEF", continent_id: 7},
  {code: "VG", name: "British Virgin Islands", native: "British Virgin Islands", phone: "1284", capital: "Road Town", currency: "USD", continent_id: 5},
  {code: "VI", name: "U.S. Virgin Islands", native: "United States Virgin Islands", phone: "1340", capital: "Charlotte Amalie", currency: "USD", continent_id: 5},
  {code: "VN", name: "Vietnam", native: "Việt Nam", phone: "84", capital: "Hanoi", currency: "VND", continent_id: 3},
  {code: "VU", name: "Vanuatu", native: "Vanuatu", phone: "678", capital: "Port Vila", currency: "VUV", continent_id: 6},
  {code: "WF", name: "Wallis and Futuna", native: "Wallis et Futuna", phone: "681", capital: "Mata-Utu", currency: "XPF", continent_id: 6},
  {code: "WS", name: "Samoa", native: "Samoa", phone: "685", capital: "Apia", currency: "WST", continent_id: 6},
  {code: "XK", name: "Kosovo", native: "Republika e Kosovës", phone: "377,381,383,386", capital: "Pristina", currency: "EUR", continent_id: 4},
  {code: "YE", name: "Yemen", native: "اليَمَن", phone: "967", capital: "Sana'a", currency: "YER", continent_id: 3},
  {code: "YT", name: "Mayotte", native: "Mayotte", phone: "262", capital: "Mamoudzou", currency: "EUR", continent_id: 1},
  {code: "ZA", name: "South Africa", native: "South Africa", phone: "27", capital: "Pretoria", currency: "ZAR", continent_id: 1},
  {code: "ZM", name: "Zambia", native: "Zambia", phone: "260", capital: "Lusaka", currency: "ZMK", continent_id: 1},
  {code: "ZW", name: "Zimbabwe", native: "Zimbabwe", phone: "263", capital: "Harare", currency: "ZWL", continent_id: 1}
])
CountryLanguage.create!([
  {country_id: 1, language_id: 11},
  {country_id: 2, language_id: 3},
  {country_id: 3, language_id: 78},
  {country_id: 3, language_id: 102},
  {country_id: 3, language_id: 109},
  {country_id: 4, language_id: 19},
  {country_id: 5, language_id: 19},
  {country_id: 6, language_id: 92},
  {country_id: 7, language_id: 38},
  {country_id: 7, language_id: 83},
  {country_id: 8, language_id: 79},
  {country_id: 10, language_id: 20},
  {country_id: 10, language_id: 31},
  {country_id: 11, language_id: 19},
  {country_id: 11, language_id: 89},
  {country_id: 12, language_id: 15},
  {country_id: 13, language_id: 19},
  {country_id: 14, language_id: 70},
  {country_id: 14, language_id: 76},
  {country_id: 15, language_id: 96},
  {country_id: 16, language_id: 5},
  {country_id: 17, language_id: 10},
  {country_id: 17, language_id: 35},
  {country_id: 17, language_id: 93},
  {country_id: 18, language_id: 19},
  {country_id: 19, language_id: 9},
  {country_id: 20, language_id: 15},
  {country_id: 20, language_id: 28},
  {country_id: 20, language_id: 70},
  {country_id: 21, language_id: 24},
  {country_id: 21, language_id: 28},
  {country_id: 22, language_id: 7},
  {country_id: 23, language_id: 3},
  {country_id: 24, language_id: 28},
  {country_id: 24, language_id: 81},
  {country_id: 25, language_id: 28},
  {country_id: 26, language_id: 28},
  {country_id: 27, language_id: 19},
  {country_id: 28, language_id: 63},
  {country_id: 29, language_id: 4},
  {country_id: 29, language_id: 20},
  {country_id: 29, language_id: 80},
  {country_id: 30, language_id: 70},
  {country_id: 31, language_id: 79},
  {country_id: 32, language_id: 19},
  {country_id: 33, language_id: 17},
  {country_id: 34, language_id: 67},
  {country_id: 34, language_id: 71},
  {country_id: 34, language_id: 72},
  {country_id: 35, language_id: 19},
  {country_id: 35, language_id: 103},
  {country_id: 36, language_id: 6},
  {country_id: 36, language_id: 83},
  {country_id: 37, language_id: 19},
  {country_id: 37, language_id: 20},
  {country_id: 38, language_id: 19},
  {country_id: 38, language_id: 28},
  {country_id: 39, language_id: 19},
  {country_id: 40, language_id: 28},
  {country_id: 40, language_id: 44},
  {country_id: 40, language_id: 53},
  {country_id: 40, language_id: 56},
  {country_id: 40, language_id: 97},
  {country_id: 41, language_id: 28},
  {country_id: 41, language_id: 85},
  {country_id: 42, language_id: 28},
  {country_id: 42, language_id: 53},
  {country_id: 43, language_id: 15},
  {country_id: 43, language_id: 28},
  {country_id: 43, language_id: 41},
  {country_id: 44, language_id: 28},
  {country_id: 45, language_id: 19},
  {country_id: 46, language_id: 20},
  {country_id: 47, language_id: 19},
  {country_id: 47, language_id: 28},
  {country_id: 48, language_id: 113},
  {country_id: 49, language_id: 20},
  {country_id: 50, language_id: 20},
  {country_id: 51, language_id: 20},
  {country_id: 52, language_id: 79},
  {country_id: 53, language_id: 19},
  {country_id: 53, language_id: 70},
  {country_id: 53, language_id: 76},
  {country_id: 54, language_id: 19},
  {country_id: 55, language_id: 18},
  {country_id: 55, language_id: 38},
  {country_id: 55, language_id: 105},
  {country_id: 56, language_id: 13},
  {country_id: 56, language_id: 87},
  {country_id: 57, language_id: 15},
  {country_id: 58, language_id: 3},
  {country_id: 58, language_id: 28},
  {country_id: 59, language_id: 14},
  {country_id: 60, language_id: 19},
  {country_id: 61, language_id: 20},
  {country_id: 62, language_id: 3},
  {country_id: 63, language_id: 20},
  {country_id: 64, language_id: 21},
  {country_id: 65, language_id: 3},
  {country_id: 66, language_id: 20},
  {country_id: 67, language_id: 3},
  {country_id: 67, language_id: 19},
  {country_id: 67, language_id: 101},
  {country_id: 68, language_id: 11},
  {country_id: 68, language_id: 20},
  {country_id: 68, language_id: 22},
  {country_id: 68, language_id: 30},
  {country_id: 68, language_id: 75},
  {country_id: 69, language_id: 2},
  {country_id: 70, language_id: 25},
  {country_id: 70, language_id: 96},
  {country_id: 71, language_id: 19},
  {country_id: 71, language_id: 26},
  {country_id: 71, language_id: 34},
  {country_id: 71, language_id: 108},
  {country_id: 72, language_id: 19},
  {country_id: 73, language_id: 19},
  {country_id: 74, language_id: 27},
  {country_id: 75, language_id: 28},
  {country_id: 76, language_id: 28},
  {country_id: 77, language_id: 19},
  {country_id: 78, language_id: 19},
  {country_id: 79, language_id: 43},
  {country_id: 80, language_id: 28},
  {country_id: 81, language_id: 19},
  {country_id: 81, language_id: 28},
  {country_id: 82, language_id: 19},
  {country_id: 83, language_id: 19},
  {country_id: 84, language_id: 46},
  {country_id: 85, language_id: 19},
  {country_id: 86, language_id: 24},
  {country_id: 86, language_id: 28},
  {country_id: 87, language_id: 28},
  {country_id: 88, language_id: 20},
  {country_id: 88, language_id: 28},
  {country_id: 89, language_id: 18},
  {country_id: 90, language_id: 19},
  {country_id: 91, language_id: 20},
  {country_id: 92, language_id: 12},
  {country_id: 92, language_id: 19},
  {country_id: 92, language_id: 20},
  {country_id: 93, language_id: 79},
  {country_id: 94, language_id: 19},
  {country_id: 95, language_id: 19},
  {country_id: 95, language_id: 113},
  {country_id: 96, language_id: 19},
  {country_id: 97, language_id: 20},
  {country_id: 98, language_id: 35},
  {country_id: 99, language_id: 28},
  {country_id: 99, language_id: 36},
  {country_id: 100, language_id: 37},
  {country_id: 101, language_id: 39},
  {country_id: 102, language_id: 19},
  {country_id: 102, language_id: 29},
  {country_id: 103, language_id: 3},
  {country_id: 103, language_id: 33},
  {country_id: 104, language_id: 19},
  {country_id: 104, language_id: 32},
  {country_id: 105, language_id: 19},
  {country_id: 105, language_id: 34},
  {country_id: 106, language_id: 19},
  {country_id: 107, language_id: 3},
  {country_id: 107, language_id: 49},
  {country_id: 108, language_id: 23},
  {country_id: 109, language_id: 40},
  {country_id: 110, language_id: 41},
  {country_id: 111, language_id: 19},
  {country_id: 111, language_id: 28},
  {country_id: 112, language_id: 19},
  {country_id: 113, language_id: 3},
  {country_id: 114, language_id: 42},
  {country_id: 115, language_id: 19},
  {country_id: 115, language_id: 97},
  {country_id: 116, language_id: 50},
  {country_id: 116, language_id: 83},
  {country_id: 117, language_id: 47},
  {country_id: 118, language_id: 19},
  {country_id: 119, language_id: 3},
  {country_id: 119, language_id: 28},
  {country_id: 120, language_id: 19},
  {country_id: 121, language_id: 48},
  {country_id: 122, language_id: 48},
  {country_id: 123, language_id: 3},
  {country_id: 124, language_id: 19},
  {country_id: 125, language_id: 45},
  {country_id: 125, language_id: 83},
  {country_id: 126, language_id: 54},
  {country_id: 127, language_id: 3},
  {country_id: 127, language_id: 28},
  {country_id: 128, language_id: 19},
  {country_id: 129, language_id: 15},
  {country_id: 130, language_id: 86},
  {country_id: 130, language_id: 98},
  {country_id: 131, language_id: 19},
  {country_id: 132, language_id: 19},
  {country_id: 132, language_id: 95},
  {country_id: 133, language_id: 55},
  {country_id: 134, language_id: 15},
  {country_id: 134, language_id: 28},
  {country_id: 134, language_id: 52},
  {country_id: 135, language_id: 57},
  {country_id: 136, language_id: 3},
  {country_id: 137, language_id: 3},
  {country_id: 138, language_id: 28},
  {country_id: 139, language_id: 82},
  {country_id: 140, language_id: 10},
  {country_id: 140, language_id: 35},
  {country_id: 140, language_id: 92},
  {country_id: 140, language_id: 93},
  {country_id: 141, language_id: 19},
  {country_id: 141, language_id: 28},
  {country_id: 141, language_id: 70},
  {country_id: 142, language_id: 28},
  {country_id: 142, language_id: 58},
  {country_id: 143, language_id: 19},
  {country_id: 143, language_id: 59},
  {country_id: 144, language_id: 61},
  {country_id: 145, language_id: 28},
  {country_id: 146, language_id: 65},
  {country_id: 147, language_id: 62},
  {country_id: 148, language_id: 79},
  {country_id: 148, language_id: 113},
  {country_id: 149, language_id: 12},
  {country_id: 149, language_id: 19},
  {country_id: 150, language_id: 28},
  {country_id: 151, language_id: 3},
  {country_id: 152, language_id: 19},
  {country_id: 153, language_id: 19},
  {country_id: 153, language_id: 64},
  {country_id: 154, language_id: 19},
  {country_id: 155, language_id: 16},
  {country_id: 156, language_id: 19},
  {country_id: 156, language_id: 74},
  {country_id: 157, language_id: 20},
  {country_id: 158, language_id: 63},
  {country_id: 159, language_id: 79},
  {country_id: 160, language_id: 1},
  {country_id: 160, language_id: 19},
  {country_id: 161, language_id: 28},
  {country_id: 162, language_id: 28},
  {country_id: 163, language_id: 19},
  {country_id: 164, language_id: 19},
  {country_id: 165, language_id: 20},
  {country_id: 166, language_id: 70},
  {country_id: 167, language_id: 67},
  {country_id: 167, language_id: 71},
  {country_id: 167, language_id: 72},
  {country_id: 168, language_id: 69},
  {country_id: 169, language_id: 19},
  {country_id: 169, language_id: 66},
  {country_id: 170, language_id: 19},
  {country_id: 171, language_id: 19},
  {country_id: 171, language_id: 60},
  {country_id: 172, language_id: 3},
  {country_id: 173, language_id: 20},
  {country_id: 174, language_id: 20},
  {country_id: 175, language_id: 28},
  {country_id: 176, language_id: 19},
  {country_id: 177, language_id: 19},
  {country_id: 178, language_id: 19},
  {country_id: 178, language_id: 108},
  {country_id: 179, language_id: 77},
  {country_id: 180, language_id: 28},
  {country_id: 181, language_id: 19},
  {country_id: 182, language_id: 19},
  {country_id: 182, language_id: 20},
  {country_id: 183, language_id: 3},
  {country_id: 184, language_id: 79},
  {country_id: 185, language_id: 19},
  {country_id: 186, language_id: 20},
  {country_id: 186, language_id: 31},
  {country_id: 187, language_id: 3},
  {country_id: 188, language_id: 28},
  {country_id: 189, language_id: 82},
  {country_id: 190, language_id: 93},
  {country_id: 191, language_id: 83},
  {country_id: 192, language_id: 19},
  {country_id: 192, language_id: 28},
  {country_id: 192, language_id: 84},
  {country_id: 193, language_id: 3},
  {country_id: 194, language_id: 19},
  {country_id: 195, language_id: 19},
  {country_id: 195, language_id: 28},
  {country_id: 196, language_id: 3},
  {country_id: 196, language_id: 19},
  {country_id: 197, language_id: 96},
  {country_id: 198, language_id: 19},
  {country_id: 198, language_id: 63},
  {country_id: 198, language_id: 98},
  {country_id: 198, language_id: 113},
  {country_id: 199, language_id: 19},
  {country_id: 200, language_id: 88},
  {country_id: 201, language_id: 72},
  {country_id: 202, language_id: 87},
  {country_id: 203, language_id: 19},
  {country_id: 204, language_id: 41},
  {country_id: 205, language_id: 28},
  {country_id: 206, language_id: 3},
  {country_id: 206, language_id: 91},
  {country_id: 207, language_id: 70},
  {country_id: 208, language_id: 19},
  {country_id: 209, language_id: 79},
  {country_id: 210, language_id: 20},
  {country_id: 211, language_id: 19},
  {country_id: 211, language_id: 70},
  {country_id: 212, language_id: 3},
  {country_id: 213, language_id: 19},
  {country_id: 213, language_id: 94},
  {country_id: 214, language_id: 19},
  {country_id: 215, language_id: 3},
  {country_id: 215, language_id: 28},
  {country_id: 216, language_id: 28},
  {country_id: 217, language_id: 28},
  {country_id: 218, language_id: 100},
  {country_id: 219, language_id: 83},
  {country_id: 219, language_id: 99},
  {country_id: 220, language_id: 19},
  {country_id: 221, language_id: 79},
  {country_id: 222, language_id: 83},
  {country_id: 222, language_id: 102},
  {country_id: 223, language_id: 3},
  {country_id: 224, language_id: 19},
  {country_id: 224, language_id: 104},
  {country_id: 225, language_id: 105},
  {country_id: 226, language_id: 19},
  {country_id: 227, language_id: 19},
  {country_id: 228, language_id: 113},
  {country_id: 229, language_id: 19},
  {country_id: 229, language_id: 97},
  {country_id: 230, language_id: 107},
  {country_id: 231, language_id: 19},
  {country_id: 231, language_id: 97},
  {country_id: 232, language_id: 19},
  {country_id: 233, language_id: 19},
  {country_id: 234, language_id: 20},
  {country_id: 235, language_id: 83},
  {country_id: 235, language_id: 109},
  {country_id: 236, language_id: 41},
  {country_id: 236, language_id: 51},
  {country_id: 237, language_id: 19},
  {country_id: 238, language_id: 20},
  {country_id: 239, language_id: 19},
  {country_id: 240, language_id: 19},
  {country_id: 241, language_id: 111},
  {country_id: 242, language_id: 8},
  {country_id: 242, language_id: 19},
  {country_id: 242, language_id: 28},
  {country_id: 243, language_id: 28},
  {country_id: 244, language_id: 19},
  {country_id: 244, language_id: 89},
  {country_id: 245, language_id: 92},
  {country_id: 245, language_id: 93},
  {country_id: 246, language_id: 3},
  {country_id: 247, language_id: 28},
  {country_id: 248, language_id: 1},
  {country_id: 248, language_id: 19},
  {country_id: 248, language_id: 73},
  {country_id: 248, language_id: 94},
  {country_id: 248, language_id: 95},
  {country_id: 249, language_id: 19},
  {country_id: 250, language_id: 19},
  {country_id: 250, language_id: 68},
  {country_id: 250, language_id: 90}
])
Language.create!([
  {code: "af", name: "Afrikaans", native: "Afrikaans", rtl: false},
  {code: "am", name: "Amharic", native: "አማርኛ", rtl: false},
  {code: "ar", name: "Arabic", native: "العربية", rtl: true},
  {code: "ay", name: "Aymara", native: "Aymar", rtl: false},
  {code: "az", name: "Azerbaijani", native: "Azərbaycanca / آذربايجان", rtl: false},
  {code: "be", name: "Belarusian", native: "Беларуская", rtl: false},
  {code: "bg", name: "Bulgarian", native: "Български", rtl: false},
  {code: "bi", name: "Bislama", native: "Bislama", rtl: false},
  {code: "bn", name: "Bengali", native: "বাংলা", rtl: false},
  {code: "bs", name: "Bosnian", native: "Bosanski", rtl: false},
  {code: "ca", name: "Catalan", native: "Català", rtl: false},
  {code: "ch", name: "Chamorro", native: "Chamoru", rtl: false},
  {code: "cs", name: "Czech", native: "Česky", rtl: false},
  {code: "da", name: "Danish", native: "Dansk", rtl: false},
  {code: "de", name: "German", native: "Deutsch", rtl: false},
  {code: "dv", name: "Divehi", native: "ދިވެހިބަސް", rtl: true},
  {code: "dz", name: "Dzongkha", native: "ཇོང་ཁ", rtl: false},
  {code: "el", name: "Greek", native: "Ελληνικά", rtl: false},
  {code: "en", name: "English", native: "English", rtl: false},
  {code: "es", name: "Spanish", native: "Español", rtl: false},
  {code: "et", name: "Estonian", native: "Eesti", rtl: false},
  {code: "eu", name: "Basque", native: "Euskara", rtl: false},
  {code: "fa", name: "Persian", native: "فارسی", rtl: true},
  {code: "ff", name: "Peul", native: "Fulfulde", rtl: false},
  {code: "fi", name: "Finnish", native: "Suomi", rtl: false},
  {code: "fj", name: "Fijian", native: "Na Vosa Vakaviti", rtl: false},
  {code: "fo", name: "Faroese", native: "Føroyskt", rtl: false},
  {code: "fr", name: "French", native: "Français", rtl: false},
  {code: "ga", name: "Irish", native: "Gaeilge", rtl: false},
  {code: "gl", name: "Galician", native: "Galego", rtl: false},
  {code: "gn", name: "Guarani", native: "Avañe'ẽ", rtl: false},
  {code: "gv", name: "Manx", native: "Gaelg", rtl: false},
  {code: "he", name: "Hebrew", native: "עברית", rtl: true},
  {code: "hi", name: "Hindi", native: "हिन्दी", rtl: false},
  {code: "hr", name: "Croatian", native: "Hrvatski", rtl: false},
  {code: "ht", name: "Haitian", native: "Krèyol ayisyen", rtl: false},
  {code: "hu", name: "Hungarian", native: "Magyar", rtl: false},
  {code: "hy", name: "Armenian", native: "Հայերեն", rtl: false},
  {code: "id", name: "Indonesian", native: "Bahasa Indonesia", rtl: false},
  {code: "is", name: "Icelandic", native: "Íslenska", rtl: false},
  {code: "it", name: "Italian", native: "Italiano", rtl: false},
  {code: "ja", name: "Japanese", native: "日本語", rtl: false},
  {code: "ka", name: "Georgian", native: "ქართული", rtl: false},
  {code: "kg", name: "Kongo", native: "KiKongo", rtl: false},
  {code: "kk", name: "Kazakh", native: "Қазақша", rtl: false},
  {code: "kl", name: "Greenlandic", native: "Kalaallisut", rtl: false},
  {code: "km", name: "Cambodian", native: "ភាសាខ្មែរ", rtl: false},
  {code: "ko", name: "Korean", native: "한국어", rtl: false},
  {code: "ku", name: "Kurdish", native: "Kurdî / كوردی", rtl: true},
  {code: "ky", name: "Kirghiz", native: "Kırgızca / Кыргызча", rtl: false},
  {code: "la", name: "Latin", native: "Latina", rtl: false},
  {code: "lb", name: "Luxembourgish", native: "Lëtzebuergesch", rtl: false},
  {code: "ln", name: "Lingala", native: "Lingála", rtl: false},
  {code: "lo", name: "Laotian", native: "ລາວ / Pha xa lao", rtl: false},
  {code: "lt", name: "Lithuanian", native: "Lietuvių", rtl: false},
  {code: "lu", name: "", native: "", rtl: false},
  {code: "lv", name: "Latvian", native: "Latviešu", rtl: false},
  {code: "mg", name: "Malagasy", native: "Malagasy", rtl: false},
  {code: "mh", name: "Marshallese", native: "Kajin Majel / Ebon", rtl: false},
  {code: "mi", name: "Maori", native: "Māori", rtl: false},
  {code: "mk", name: "Macedonian", native: "Македонски", rtl: false},
  {code: "mn", name: "Mongolian", native: "Монгол", rtl: false},
  {code: "ms", name: "Malay", native: "Bahasa Melayu", rtl: false},
  {code: "mt", name: "Maltese", native: "bil-Malti", rtl: false},
  {code: "my", name: "Burmese", native: "Myanmasa", rtl: false},
  {code: "na", name: "Nauruan", native: "Dorerin Naoero", rtl: false},
  {code: "nb", name: "", native: "", rtl: false},
  {code: "nd", name: "North Ndebele", native: "Sindebele", rtl: false},
  {code: "ne", name: "Nepali", native: "नेपाली", rtl: false},
  {code: "nl", name: "Dutch", native: "Nederlands", rtl: false},
  {code: "nn", name: "Norwegian Nynorsk", native: "Norsk (nynorsk)", rtl: false},
  {code: "no", name: "Norwegian", native: "Norsk (bokmål / riksmål)", rtl: false},
  {code: "nr", name: "South Ndebele", native: "isiNdebele", rtl: false},
  {code: "ny", name: "Chichewa", native: "Chi-Chewa", rtl: false},
  {code: "oc", name: "Occitan", native: "Occitan", rtl: false},
  {code: "pa", name: "Panjabi / Punjabi", native: "ਪੰਜਾਬੀ / पंजाबी / پنجابي", rtl: false},
  {code: "pl", name: "Polish", native: "Polski", rtl: false},
  {code: "ps", name: "Pashto", native: "پښتو", rtl: true},
  {code: "pt", name: "Portuguese", native: "Português", rtl: false},
  {code: "qu", name: "Quechua", native: "Runa Simi", rtl: false},
  {code: "rn", name: "Kirundi", native: "Kirundi", rtl: false},
  {code: "ro", name: "Romanian", native: "Română", rtl: false},
  {code: "ru", name: "Russian", native: "Русский", rtl: false},
  {code: "rw", name: "Rwandi", native: "Kinyarwandi", rtl: false},
  {code: "sg", name: "Sango", native: "Sängö", rtl: false},
  {code: "si", name: "Sinhalese", native: "සිංහල", rtl: false},
  {code: "sk", name: "Slovak", native: "Slovenčina", rtl: false},
  {code: "sl", name: "Slovenian", native: "Slovenščina", rtl: false},
  {code: "sm", name: "Samoan", native: "Gagana Samoa", rtl: false},
  {code: "sn", name: "Shona", native: "chiShona", rtl: false},
  {code: "so", name: "Somalia", native: "Soomaaliga", rtl: false},
  {code: "sq", name: "Albanian", native: "Shqip", rtl: false},
  {code: "sr", name: "Serbian", native: "Српски", rtl: false},
  {code: "ss", name: "Swati", native: "SiSwati", rtl: false},
  {code: "st", name: "Southern Sotho", native: "Sesotho", rtl: false},
  {code: "sv", name: "Swedish", native: "Svenska", rtl: false},
  {code: "sw", name: "Swahili", native: "Kiswahili", rtl: false},
  {code: "ta", name: "Tamil", native: "தமிழ்", rtl: false},
  {code: "tg", name: "Tajik", native: "Тоҷикӣ", rtl: false},
  {code: "th", name: "Thai", native: "ไทย / Phasa Thai", rtl: false},
  {code: "ti", name: "Tigrinya", native: "ትግርኛ", rtl: false},
  {code: "tk", name: "Turkmen", native: "Туркмен / تركمن", rtl: false},
  {code: "tn", name: "Tswana", native: "Setswana", rtl: false},
  {code: "to", name: "Tonga", native: "Lea Faka-Tonga", rtl: false},
  {code: "tr", name: "Turkish", native: "Türkçe", rtl: false},
  {code: "ts", name: "Tsonga", native: "Xitsonga", rtl: false},
  {code: "uk", name: "Ukrainian", native: "Українська", rtl: false},
  {code: "ur", name: "Urdu", native: "اردو", rtl: true},
  {code: "uz", name: "Uzbek", native: "Ўзбек", rtl: false},
  {code: "ve", name: "Venda", native: "Tshivenḓa", rtl: false},
  {code: "vi", name: "Vietnamese", native: "Tiếng Việt", rtl: false},
  {code: "xh", name: "Xhosa", native: "isiXhosa", rtl: false},
  {code: "zh", name: "Chinese", native: "中文", rtl: false},
  {code: "zu", name: "Zulu", native: "isiZulu", rtl: false}
])
